// <auto-generated />
using CoreAppSinav.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreAppSinav.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220604174747_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreAppSinav.Models.Departmanlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmanAd")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Detay")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("ID");

                    b.ToTable("GorevDepartmans");
                });

            modelBuilder.Entity("CoreAppSinav.Models.Personel", b =>
                {
                    b.Property<int>("perid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("departid")
                        .HasColumnType("int");

                    b.Property<string>("sehir")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("soyad")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("perid");

                    b.HasIndex("departid");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("CoreAppSinav.Models.Personel", b =>
                {
                    b.HasOne("CoreAppSinav.Models.Departmanlar", "depart")
                        .WithMany("_Personels")
                        .HasForeignKey("departid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depart");
                });

            modelBuilder.Entity("CoreAppSinav.Models.Departmanlar", b =>
                {
                    b.Navigation("_Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
